Add manuscript links to readme
greenelab/covid19-review pull request #1048
Opened 2021-09-24 20:00 UTC by rando2

### Description of the proposed additions or changes

Propose moving the table from #731 to the front page, to help orient people

### Related issues

### Suggested reviewers (optional)

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

2021-09-25 13:35 UTC, agitter requested changes
This looks great.  The original suggestion to add a splash page came from [this reader](https://twitter.com/BioinfoTools/status/1440061438429519881).

Should we order the table rows as they appear in the merged review?  Sorting by submission date made sense when the table was oriented toward authors, but now it is for external readers as well.

2021-09-25 13:35 UTC, agitter commented on README.md
> +| Pathogenesis | Pathogenesis, Symptomatology, and Transmission of SARS-CoV-2 through analysis of Viral Genomics and Structure | #744 | Ready for resubmission | _mSystems_ | [Release](https://github.
```suggestion
| [Pathogenesis](https://greenelab.github.io/covid19-review/#pathogenesis-symptomatology-and-transmission-of-sars-cov-2-through-analysis-of-viral-genomics-and-structure) | Pathogenesis, Symptomatology, and Transmission of SARS-CoV-2 through analysis of Viral Genomics and Structure | #744 | Ready for resubmission | _mSystems_ | [Release](https://github.com/greenelab/covid19-review/releases/tag/pathogenesis-v2); [Preprint](http://arxiv.org/abs/2102.01521)
```
What do you think about linking the first column to where the paper appears in the merged review?  That will help readers find the absolute latest version if they're interested.  Those links should be stable as long as the section titles do not change.

We can get the URLs from the table of contents in the HTML manuscript.

2021-09-25 19:27 UTC, agitter commented on README.md
> +| Methods (Cyberinfrastructure) | An Open-Publishing Response to the COVID-19 Infodemic | ✔️ | Accepted | [DISCO 2021](https://infoqualitylab.org/events/disco2021/) | [Release](https://github.com/gre
```suggestion
| [Methods (Cyberinfrastructure)](https://greenelab.github.io/covid19-review/#an-open-publishing-response-to-the-covid-19-infodemic) | An Open-Publishing Response to the COVID-19 Infodemic | ✔️ | Accepted | [DISCO 2021](https://infoqualitylab.org/events/disco2021/) | [Release](https://github.com/greenelab/covid19-review/releases/tag/methods-v3); [Preprint](https://arxiv.org/abs/2109.08633)
```

Updating with the latest release I just made.

2021-09-28 18:22 UTC, agitter commented on README.md
> +| [Pathogenesis](https://greenelab.github.io/covid19-review/#pathogenesis-symptomatology-and-transmission-of-sars-cov-2-through-analysis-of-viral-genomics-and-structure) | Pathogenesis, Symptomatolog
```suggestion
| [Pathogenesis](https://greenelab.github.io/covid19-review/#pathogenesis-symptomatology-and-transmission-of-sars-cov-2-through-analysis-of-viral-genomics-and-structure) | Pathogenesis, Symptomatology, and Transmission of SARS-CoV-2 through analysis of Viral Genomics and Structure | ✔️ | Accepted | _mSystems_ | [Release](https://github.com/greenelab/covid19-review/releases/tag/pathogenesis-v2); [Preprint](http://arxiv.org/abs/2102.01521)
```

2021-09-28 18:58 UTC, agitter approved these changes

2021-09-28 18:58 UTC, rando2 commented
Thank you for making that update @agitter! I got notice today they posted the new version of the preprint, so I believe everything should be up to date now!

2021-09-28 19:28 UTC, merged