Add one sentence defining Type III CRISPR
greenelab/covid19-review pull request #1093
Opened 2022-03-15 14:46 UTC by rando2

### Description of the proposed additions or changes

Add a definition of Type III CRISPR, per @nilswellhausen comment
Feel free to edit or suggest alternatives!

### Related issues

### Suggested reviewers (optional)

@nilswellhausen @SystemsResearch @jessegmeyerlab

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

2022-03-16 00:49 UTC, SystemsResearch requested changes
I think the sentence is fine.

I also had a read through the whole section again and checked the references. Two of the preprints have now been published:

- 10.1101/2020.10.14.20212670 on line 201 has been published as 10.1016/j.xcrm.2021.100319
- 10.1101/2020.09.13.20193581 on line 219 has been published as 10.1016/j.bios.2021.113207

Should they be updated?

2022-03-16 14:35 UTC, RLordan approved these changes

2022-03-16 19:22 UTC, rando2 commented on content/10.diagnostics.md
>  A study tested this hypothesis using the type III-A CRISPR RNA (crRNA)-guided surveillance complex from Thermus thermophilus [@doi:10.1101/2020.10.14.20212670].
Update to published doi? 10.1016/j.xcrm.2021.100319

2022-03-17 00:26 UTC, SystemsResearch commented
@rando2 I agree this is a sensible solution: we cite the published version and just remove the statement that has disappeared in that version.

2022-03-17 13:40 UTC, rando2 commented on content/10.diagnostics.md
>  A study tested this hypothesis using the type III-A CRISPR RNA (crRNA)-guided surveillance complex from Thermus thermophilus [@doi:10.1101/2020.10.14.20212670].
```suggestion
A study tested this hypothesis using the type III-A CRISPR RNA (crRNA)-guided surveillance complex from _Thermus thermophilus_ [@doi:10.1016/j.xcrm.2021.100319]. 
```

2022-03-17 13:40 UTC, rando2 commented on content/10.diagnostics.md
> +Direct detection was 100-fold more sensitive than direct detection by Cas13.
```suggestion
```

2022-03-17 16:09 UTC, merged