Proposed vaccine author list
greenelab/covid19-review pull request #1160
Opened 2022-06-21 19:02 UTC by rando2

### Description of the proposed additions or changes

Here is my proposed plan for author order. Please feel free to indicate if you think something doesn't look right. Here's the data I pulled:

Author/username | contributions | Order - Trad | Order - Novel | # lines
-- | -- | -- | -- | --
Anthony Gitter   | software and editing | 8 | 8 | 39
Casey Greene | mRNA | 7 | 9 |  
HM Rando   |   | 1 | 1 | 5514
Ronan Lordan  |   | 2 | 2 | 1055
likhithakolla   | mRNA | 5 | 3 | 116
Elizabeth (Ellie) Sell  | DNA | 4 | 4 | 42
Alexandra Lee  | whole-virus | 3 | 5 | 375
nilswellhausen    | novavax | 3 | 5 | 205
NAIKA86   | COVAXIN | 3 | 6 | 36
John J. Dziak   |   | ack | ack | 2
Consortium |   | 6 | 7 |  

I made a note where people had taken a major role in contributing to a particular vaccine write-up.

### Related issues

#830

### Suggested reviewers (optional)

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

2022-06-24 04:01 UTC, RLordan approved these changes

2022-06-25 17:03 UTC, agitter requested changes
We can continue the convention of Casey being last author.

2022-06-25 17:03 UTC, agitter commented on content/metadata.yaml
> +          - Project Administration
Did Nils contribute to the writing for either manuscript? I see some lines edited in your summary table.

2022-06-25 17:03 UTC, agitter commented on content/metadata.yaml
> +        order: 8
```suggestion
        order: 7
```

2022-07-07 13:20 UTC, rando2 commented on content/metadata.yaml
> +          - Project Administration
```suggestion
          - Project Administration
          - Writing - Review & Editing          
```
Thank you! I missed this one!

2022-07-09 02:49 UTC, agitter approved these changes

2022-07-26 17:47 UTC, merged