Add Simina's comments from #643
greenelab/covid19-review pull request #650
Opened 2020-10-09 22:13 UTC by rando2

### Description of the proposed additions or changes

Simina had some suggestions that didn't make it in when #643 merged. I believe this implements all of them except 2:
1. I couldn't find "sited"!
2. I learned this work from Ronan, but I believe he did mean "evinced" (reveal the presence of)!

### Related issues

#643 

### Suggested reviewers (optional)

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

2020-10-10 04:26 UTC, SiminaB commented
"Sited" was actually in 50.discussion.md - sorry for not stating that earlier!

2020-10-12 05:03 UTC, SiminaB requested changes
"Sited" was actually in 50.discussion.md - sorry for not stating that clearly before.

I found some of the sentences about the BCG vaccine (also in 50.discussion.md) to be a bit awkward, but don't need to make those changes before merging this one.

2020-10-12 13:59 UTC, rando2 commented
Hi @SiminaB, Excellent! 50 definitely needs work, I'm working on that section this week so I'm sure I'll be tagging you on lots of PRs!

If this looks OK, do you mind switching your review to approve? I will definitely make sure you're looped in on changes to the discussion!

2020-10-12 14:12 UTC, SiminaB approved these changes

2020-10-12 15:33 UTC, merged