Proposed content of pathogenesis/transmission manuscript
greenelab/covid19-review pull request #745
Opened 2020-12-21 19:28 UTC by rando2

### Description of the proposed additions or changes

This PR proposes the text that will be one of the manuscripts, focusing on pathogenesis and transmission. The introduction and discussion are new text, other edits were just cleaning up the existing text.

### Related issues

#744 

### Suggested reviewers (optional)

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

2021-01-08 21:33 UTC, dziakj1 approved these changes

2021-01-08 22:49 UTC, nilswellhausen approved these changes

2021-01-09 08:10 UTC, RLordan requested changes
Hey @rando2 some suggested edits here. The transmission bit is probably the most important bit to clarify. Thanks a million!

2021-01-09 08:10 UTC, RLordan commented on content/07.pathogenesis.md
> +While the extent to which aerosol and fomite transmission play a role in the spread of SARS-CoV-2, in general this virus seems to be spread primarily by droplet transmission, much like SARS-CoV-1 and
I was reading the transmission section and this conclusion. I think there is a lot less emphasis these days on fomite transmission and much more emphasis on transmission by respiratory droplets within close contact. Certainly fomite transmission does occur, but the CDC does not acknowledge it as the main route. I would have edited, but I don’t know who wrote this section so they may want to review it themselves.

https://www.cdc.gov/coronavirus/2019-ncov/more/scientific-brief-sars-cov-2.html
https://www.cdc.gov/coronavirus/2019-ncov/faq.html#Spread

2021-01-09 08:10 UTC, RLordan commented on content/07.pathogenesis.md
> +While the structure of the viruses are very similar, evolution among these species may account for differences in their transmissibility and virulence.
```suggestion
While the structures of the viruses are very similar, evolution among these species may account for differences in their transmissibility and virulence.
```

2021-01-10 01:20 UTC, ajlee21 approved these changes
This section looks great! Just had some very minor comments

2021-01-10 01:20 UTC, ajlee21 commented on content/40.inequality.md
> +In Brazil indigenous communities likewise carry an increased burden of COVID-19 [@doi:10.1126/science.abc0073].
```suggestion
In Brazil, indigenous communities likewise carry an increased burden of COVID-19 [@doi:10.1126/science.abc0073].
```

2021-01-10 01:20 UTC, ajlee21 commented on content/40.inequality.md
> +Similarly, evidence suggests that similar patterns might be found in other tissues: preliminary analysis suggested that male patients with aortic valve stenosis may show higher levels of ACE2 express
```suggestion
Similarly, evidence suggests that similar patterns might be found in other tissues: preliminary analysis suggested that male patients with aortic valve stenosis showed higher levels of ACE2 expression in the myocardium than females, although this pattern was not found in controls, and research indicated that females responded to lower doses of heart medications that act on a pathway shared with ACE2 (Renin angiotensin aldosterone system or RAAS) [@doi:10.1186/s13293-020-00304-9].
```

2021-01-10 01:20 UTC, ajlee21 commented on content/40.inequality.md
> +Similarly, evidence suggests that similar patterns might be found in other tissues: preliminary analysis suggested that male patients with aortic valve stenosis may show higher levels of ACE2 express
Not sure what the wording meant by "suggested" here. I wonder if it should just say `Similarly, evidence suggested that similar patterns might be found in other tissues: preliminary analysis showed that male patients with aortic valve stenosis had higher levels...`

2021-01-11 21:06 UTC, rando2 commented on content/40.inequality.md
> +Two traits that have been consistently associated with more severe COVID-19 outcomes are male sex and advanced age.
```suggestion
Two traits that have been consistently associated with more severe COVID-19 outcomes are male sex and advanced age (typically defined as 60 or older, with the greatest risk among those 85 and older [@url:https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/older-adults.html]).
```

2021-01-11 21:21 UTC, rando2 reviewed
Thank you so much @RLordan and @ajlee21 for all the feedback!

2021-01-11 21:21 UTC, rando2 commented on content/07.pathogenesis.md
> +The coming of age of genomic technologies has made these types of analyses feasible, and genomics research that characterize changes in SARS-CoV-2 along with temporal and spatial movement is likely t
```suggestion
The coming of age of genomic technologies has made these types of analyses feasible, and genomics research characterizing changes in SARS-CoV-2 along with temporal and spatial movement is likely to provide additional insights into whether within-species evolution influences the effect of the virus on the human host.
```
Minor change to @ajlee21's text suggestion

2021-01-11 21:21 UTC, rando2 commented on content/40.inequality.md
> +Similarly, evidence suggests that similar patterns might be found in other tissues: preliminary analysis suggested that male patients with aortic valve stenosis showed higher levels of ACE2 expressio
```suggestion
Similarly, evidence suggests that similar patterns might be found in other tissues.
A preliminary analysis identified higher levels of ACE2 expression in the myocardium of male patients with aortic valve stenosis showed  than female patients, although this pattern was not found in controls [@doi:10.1186/s13293-020-00304-9].
Additionally, research has indicated that females respond to lower doses than males of heart medications that act on the Renin angiotensin aldosterone system (RAAS) pathway, which is shared with ACE2 [@doi:10.1186/s13293-020-00304-9].
```

@ajlee21 does this help?

2021-01-13 06:27 UTC, RLordan commented on content/07.pathogenesis.md
>  #### Pediatric Presentation
Done @rando2 , let me know if you want more detail :)

2021-01-13 06:38 UTC, RLordan commented on content/07.pathogenesis.md
> +While the extent to which aerosol and fomite transmission play a role in the spread of SARS-CoV-2, in general this virus seems to be spread primarily by droplet transmission, much like SARS-CoV-1 and
This is perfect @rando2

2021-01-13 20:44 UTC, rando2 commented
@ajlee21 and @RLordan I just wanted to check and see if these changes were sufficient to address your concerns! @RLordan if you are happy with them and don't mind changing your review, I can try to get this merged in. Thank you both again!

2021-01-13 20:47 UTC, RLordan commented
> @ajlee21 and @RLordan I just wanted to check and see if these changes were sufficient to address your concerns! @RLordan if you are happy with them and don't mind changing your review, I can try to get this merged in. Thank you both again!

Yes, super @rando2

2021-01-13 20:47 UTC, RLordan approved these changes

2021-01-13 20:51 UTC, rando2 commented
Awesome, thanks @RLordan!

2021-01-13 21:59 UTC, ajlee21 commented on content/07.pathogenesis.md
>  Additional accessory genes are sometimes present between these two regions, depending on the species or strain. <!-- TODO: Add a figure showing the structure of the genome.-->
I think visuals are always very helpful. But I wouldn't say its urgent given that there definitely exists many online for people to google. I can try to work on making one but I don't think it needs to hold up the submission

2021-01-13 22:00 UTC, ajlee21 commented
Looks good to me too. Added a response about the drawing

2021-01-13 22:07 UTC, rando2 commented on content/07.pathogenesis.md
>  Additional accessory genes are sometimes present between these two regions, depending on the species or strain. <!-- TODO: Add a figure showing the structure of the genome.-->
Thank you so much @ajlee21! @nilswellhausen is also incredibly talented at scientific visualization and may have thoughts!

2021-01-13 22:08 UTC, merged

2021-01-14 01:01 UTC, nilswellhausen commented on content/07.pathogenesis.md
>  Additional accessory genes are sometimes present between these two regions, depending on the species or strain. <!-- TODO: Add a figure showing the structure of the genome.-->
Happy to put a figure together! Are you referring to the entire pathogenesis section or a figure for a specific part ? Either way, if someone wants to send me a basic drawing (can be pen and paper style) I can make it into a figure in less than 2 hours.

2021-01-14 01:46 UTC, ajlee21 commented on content/07.pathogenesis.md
>  Additional accessory genes are sometimes present between these two regions, depending on the species or strain. <!-- TODO: Add a figure showing the structure of the genome.-->
Amazing. I think this is a figure illustrating the structure of the CoV virion particle. So I was thinking something very basic like this: https://www.google.com/search?q=covid+structure&sxsrf=ALeKk02TWfkwENRf8nrvexytwQfQvuDy8A:1610588734617&tbm=isch&source=iu&ictx=1&fir=Pr35tXoGibc1uM%252C5oS0v-dQvEwIJM%252C_&vet=1&usg=AI4_-kRs2tvodunZgUxwkX-D9EGtwckM6A&sa=X&ved=2ahUKEwiEk5_LppruAhUMGVkFHYvpDRMQ9QF6BAgYEAE&biw=2076&bih=1456#imgrc=Pr35tXoGibc1uM

2021-01-14 03:19 UTC, nilswellhausen commented on content/07.pathogenesis.md
> +Among them, alpha and beta coronaviruses infect mammalian species, gamma coronaviruses infect avian species, and delta coronaviruses infect both mammalian and avian species [@doi:10.1146/annurev-viro
![Untitled (7)](https://user-images.githubusercontent.com/62564517/104540419-6da3e600-55ed-11eb-9852-e800098a118d.png)

2021-01-14 03:20 UTC, nilswellhausen commented on content/07.pathogenesis.md
> +Among them, alpha and beta coronaviruses infect mammalian species, gamma coronaviruses infect avian species, and delta coronaviruses infect both mammalian and avian species [@doi:10.1146/annurev-viro
Let me know what you think!

2021-01-14 03:20 UTC, RLordan commented on content/07.pathogenesis.md
> +Among them, alpha and beta coronaviruses infect mammalian species, gamma coronaviruses infect avian species, and delta coronaviruses infect both mammalian and avian species [@doi:10.1146/annurev-viro
Awesome @nilswellhausen

2021-01-14 03:31 UTC, ajlee21 commented on content/07.pathogenesis.md
> +Among them, alpha and beta coronaviruses infect mammalian species, gamma coronaviruses infect avian species, and delta coronaviruses infect both mammalian and avian species [@doi:10.1146/annurev-viro
That's beautiful! Way better than anything i could've made:) Thank you

2021-01-14 14:32 UTC, rando2 commented on content/07.pathogenesis.md
> +Among them, alpha and beta coronaviruses infect mammalian species, gamma coronaviruses infect avian species, and delta coronaviruses infect both mammalian and avian species [@doi:10.1146/annurev-viro
WOW! This is incredible!!!