move anakinra to pharmaceuticals
greenelab/covid19-review pull request #757
Opened 2021-01-13 22:05 UTC by rando2

### Description of the proposed additions or changes

Replaces #605 
Due to the restructure + not having the necessary write permissions on other fork, I think this is the easiest way to get a version of #605 that can be incorporated. There was great feedback on #605 so we should keep an eye on it!

### Related issues

### Suggested reviewers (optional)

### Checklist

- [ ] Text is formatted so that each sentence is on its own line.

- [ ] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

2021-01-13 22:09 UTC, agitter commented
Do we want to work on merging #605 with this new pull request or close it?  It felt very preliminary to me.

2021-01-13 22:11 UTC, rando2 commented
@agitter I was going to try to provide feedback on the content from #605 but ran into some really bad merge conflict issues! I was planning to give my feedback here so that it can be more easily incorporated.

2021-01-13 22:57 UTC, rando2 reviewed
@athril thank you for starting all of this! I was curious, is there more content you want to add, or should I work on fleshing it out to complement the Tocilizumab section above?

2021-01-13 22:57 UTC, rando2 commented on content/20.pharmaceuticals.md
> +**Anticipated Mechanism.**
```suggestion

```
We changed the format to less explicitly use these subheadings, so I'll remove them in the text here!

2021-01-13 22:57 UTC, rando2 commented on content/20.pharmaceuticals.md
> +Anakinra is a recombinant of IL-1 receptor antagonist (IL-1Ra) that blocks binding of IL-1α, or IL-1β to IL-1R1.
```suggestion
Anakinra is a recombinant of the IL-1 receptor antagonist (IL-1Ra) and blocks the binding of IL-1α and IL-1β to IL-1R1.
```

2021-01-13 22:57 UTC, rando2 commented on content/20.pharmaceuticals.md
> +Its main task is to reduce inflammation caused by IL-1-mediation, which finds a broad spectrum of applications, including acute stroke [@doi10.1136/jnnp.2004.054882], rheumatoid arthritis [@doi:10.38
```suggestion
It is primarily used to reduce inflammation by mediating IL-1, providing a broad spectrum of applications that include the treatment of acute stroke [@doi10.1136/jnnp.2004.054882], rheumatoid arthritis [@doi:10.3899/jrheum.090074], and several hereditary, systemic or local inflammatory diseases [@doi:10.1056/NEJMoa055137, @doi:10.1186/s12969-017-0147-3, @doi:10.3389/fphar.2018.01157].
```

2021-01-13 22:57 UTC, rando2 commented on content/20.pharmaceuticals.md
> +**Current Evidence.**
```suggestion
```

2021-01-13 22:57 UTC, rando2 commented on content/20.pharmaceuticals.md
> +**Summary.**
```suggestion
```

2021-01-13 22:57 UTC, rando2 commented on content/20.pharmaceuticals.md
> +The application of Anakinra features a very safety profile, and has a very low rate of side effects and prolonged duration.
Wow, it's quite hard to find good safety profiles of Anakinra! I will keep looking.

2021-01-14 04:46 UTC, athril commented
Hi @rando2!

It's been a while since I wrote this section and I think it would be
worthwhile to revisit and update it.
Is there any specific deadline for changes?

Thank you!


On Wed, Jan 13, 2021 at 5:57 PM HM Rando <notifications@github.com> wrote:

> *@rando2* commented on this pull request.
>
> @athril <https://github.com/athril> thank you for starting all of this! I
> was curious, is there more content you want to add, or should I work on
> fleshing it out to complement the Tocilizumab section above?
> ------------------------------
>
> In content/20.pharmaceuticals.md
> <https://github.com/greenelab/covid19-review/pull/757#discussion_r556899959>
> :
>
> > @@ -651,6 +651,19 @@ Interest in TCZ as a treatment for COVID-19 was supported by two meta-analyses t
>
>  Additionally, different studies used different dosages, number of doses, and methods of administration; ongoing research may be needed to optimize administration of TCZ [@doi:10.1016/j.jcv.2020.104443], although similar results were reported by one study for intravenous and subcutaneous administration [@doi:10/d2pk].
>
>  Clinical trials that are in progress are likely to provide additional insight into the effectiveness of this drug for the treatment of COVID-19 along with how it should be administered.
>
>
>
> +###### Anakinra
>
> +**Anticipated Mechanism.**
>
>
> ⬇️ Suggested change
>
> -**Anticipated Mechanism.**
>
>
> We changed the format to less explicitly use these subheadings, so I'll
> remove them in the text here!
> ------------------------------
>
> In content/20.pharmaceuticals.md
> <https://github.com/greenelab/covid19-review/pull/757#discussion_r556905342>
> :
>
> > @@ -651,6 +651,20 @@ Interest in TCZ as a treatment for COVID-19 was supported by two meta-analyses t
>
>  Additionally, different studies used different dosages, number of doses, and methods of administration; ongoing research may be needed to optimize administration of TCZ [@doi:10.1016/j.jcv.2020.104443], although similar results were reported by one study for intravenous and subcutaneous administration [@doi:10/d2pk].
>
>  Clinical trials that are in progress are likely to provide additional insight into the effectiveness of this drug for the treatment of COVID-19 along with how it should be administered.
>
>
>
> +###### Anakinra
>
> +**Anticipated Mechanism.**
>
> +Anakinra is a recombinant of IL-1 receptor antagonist (IL-1Ra) that blocks binding of IL-1α, or IL-1β to IL-1R1.
>
>
> ⬇️ Suggested change
>
> -Anakinra is a recombinant of IL-1 receptor antagonist (IL-1Ra) that blocks binding of IL-1α, or IL-1β to IL-1R1.
>
> +Anakinra is a recombinant of the IL-1 receptor antagonist (IL-1Ra) and blocks the binding of IL-1α and IL-1β to IL-1R1.
>
>
> ------------------------------
>
> In content/20.pharmaceuticals.md
> <https://github.com/greenelab/covid19-review/pull/757#discussion_r556913724>
> :
>
> > @@ -651,6 +653,20 @@ Interest in TCZ as a treatment for COVID-19 was supported by two meta-analyses t
>
>  Additionally, different studies used different dosages, number of doses, and methods of administration; ongoing research may be needed to optimize administration of TCZ [@doi:10.1016/j.jcv.2020.104443], although similar results were reported by one study for intravenous and subcutaneous administration [@doi:10/d2pk].
>
>  Clinical trials that are in progress are likely to provide additional insight into the effectiveness of this drug for the treatment of COVID-19 along with how it should be administered.
>
>
>
> +##### Anakinra
>
> +**Anticipated Mechanism.**
>
> +Anakinra is a recombinant of IL-1 receptor antagonist (IL-1Ra) that blocks binding of IL-1α, or IL-1β to IL-1R1.
>
> +Its main task is to reduce inflammation caused by IL-1-mediation, which finds a broad spectrum of applications, including acute stroke [@doi10.1136/jnnp.2004.054882], rheumatoid arthritis [@doi:10.3899/jrheum.090074], and several hereditary, systemic or local inflammatory diseases [@doi:10.1056/NEJMoa055137, @doi:10.1186/s12969-017-0147-3, @doi:10.3389/fphar.2018.01157].
>
>
> ⬇️ Suggested change
>
> -Its main task is to reduce inflammation caused by IL-1-mediation, which finds a broad spectrum of applications, including acute stroke [@doi10.1136/jnnp.2004.054882], rheumatoid arthritis [@doi:10.3899/jrheum.090074], and several hereditary, systemic or local inflammatory diseases [@doi:10.1056/NEJMoa055137, @doi:10.1186/s12969-017-0147-3, @doi:10.3389/fphar.2018.01157].
>
> +It is primarily used to reduce inflammation by mediating IL-1, providing a broad spectrum of applications that include the treatment of acute stroke [@doi10.1136/jnnp.2004.054882], rheumatoid arthritis [@doi:10.3899/jrheum.090074], and several hereditary, systemic or local inflammatory diseases [@doi:10.1056/NEJMoa055137, @doi:10.1186/s12969-017-0147-3, @doi:10.3389/fphar.2018.01157].
>
>
> ------------------------------
>
> In content/20.pharmaceuticals.md
> <https://github.com/greenelab/covid19-review/pull/757#discussion_r556914528>
> :
>
> > +
>
> +**Current Evidence.**
>
>
> ⬇️ Suggested change
>
> -
>
> -**Current Evidence.**
>
>
> ------------------------------
>
> In content/20.pharmaceuticals.md
> <https://github.com/greenelab/covid19-review/pull/757#discussion_r556914649>
> :
>
> > @@ -651,6 +653,20 @@ Interest in TCZ as a treatment for COVID-19 was supported by two meta-analyses t
>
>  Additionally, different studies used different dosages, number of doses, and methods of administration; ongoing research may be needed to optimize administration of TCZ [@doi:10.1016/j.jcv.2020.104443], although similar results were reported by one study for intravenous and subcutaneous administration [@doi:10/d2pk].
>
>  Clinical trials that are in progress are likely to provide additional insight into the effectiveness of this drug for the treatment of COVID-19 along with how it should be administered.
>
>
>
> +##### Anakinra
>
> +**Anticipated Mechanism.**
>
> +Anakinra is a recombinant of IL-1 receptor antagonist (IL-1Ra) that blocks binding of IL-1α, or IL-1β to IL-1R1.
>
> +Its main task is to reduce inflammation caused by IL-1-mediation, which finds a broad spectrum of applications, including acute stroke [@doi10.1136/jnnp.2004.054882], rheumatoid arthritis [@doi:10.3899/jrheum.090074], and several hereditary, systemic or local inflammatory diseases [@doi:10.1056/NEJMoa055137, @doi:10.1186/s12969-017-0147-3, @doi:10.3389/fphar.2018.01157].
>
> +The application of Anakinra features a very safety profile, and has a very low rate of side effects and prolonged duration.
>
> +
>
> +**Current Evidence.**
>
> +
>
> +In two retrospective cohort studies, first at the San Raffaele Hospital in Milan, Italy with 29 patients treated with high dosages of anakinra and 16 controls [@doi:10.1016/S2665-9913(20)30127-2], and second at Groupe Hospitalier Paris Saint-Joseph Paris, France, with 96 participants in France, among which 52 were treated with the drug and 44 were administered standard protocols, anakinra has proven to progressively improve respiratory function, dicrease likelihood of application of invasive mechanical ventilation, and significantly reduce mortality [@doi:10.1016/S2665-9913(20)30164-8].
>
> +
>
> +**Summary.**
>
>
> ⬇️ Suggested change
>
> -**Summary.**
>
>
> ------------------------------
>
> In content/20.pharmaceuticals.md
> <https://github.com/greenelab/covid19-review/pull/757#discussion_r556932667>
> :
>
> > @@ -651,6 +653,20 @@ Interest in TCZ as a treatment for COVID-19 was supported by two meta-analyses t
>
>  Additionally, different studies used different dosages, number of doses, and methods of administration; ongoing research may be needed to optimize administration of TCZ [@doi:10.1016/j.jcv.2020.104443], although similar results were reported by one study for intravenous and subcutaneous administration [@doi:10/d2pk].
>
>  Clinical trials that are in progress are likely to provide additional insight into the effectiveness of this drug for the t [...]

2021-01-14 08:48 UTC, RLordan reviewed
Hey @rando2 and @athril, I gave a quick review. Feel free to add, edit, or dismiss the suggestions. Here is another paper I came across that was promising but not as significant - https://doi.org/10.1186/s13054-020-03364-w

There is certainly a few reviews out there registering their interest for anakinra.

2021-01-14 15:19 UTC, rando2 commented
Hey @athril, Thank you so much! If there's any chance to get some updates by the end of next week, I think that should work for me to give you feedback! Otherwise, we could just add a mention to anakinra as an alternative possible interleukin inhibitor and flesh it out once more data is a available!

2021-01-23 03:09 UTC, athril commented
I have found three other studies. The first one is from Dec 10, 2020:  https://doi.org/10.1186/s13054-020-03364-w
The second one (retrospective) even suggests reduced mortality with anakinra for patients not responding to  corticosteroids or corticosteroids+tocilizumab: https://doi.org/10.1007/s11739-020-02600-z
Another paper in Lancet (what a hit, from today!) is probably the first randomized trial. They claim anakinra didn't improve the outcome of mild to moderate covid19 pneumonia patients: https://www.thelancet.com/journals/lanres/article/PIIS2213-2600(20)30556-7/fulltext Will be creating the link to the patients shortly and extending the description.

2021-01-23 05:15 UTC, athril reviewed
I have added a couple of lines of text. Thank you @RLordan for your comments, I have just noticed that we have found the same papers ;)

2021-01-27 21:45 UTC, rando2 commented on content/20.pharmaceuticals.md
> +It is primarily used to reduce inflammation by mediating IL-1, providing a broad spectrum of applications that include the treatment of acute stroke [@doi10.1136/jnnp.2004.054882], rheumatoid arthrit
```suggestion
Its primary function is to reduce inflammation by mediating IL-1, providing a broad spectrum of applications that include the treatment of acute stroke [@doi10.1136/jnnp.2004.054882], rheumatoid arthritis [@doi:10.3899/jrheum.090074], and several hereditary, systemic or local inflammatory diseases [@doi:10.1056/NEJMoa055137, @doi:10.1186/s12969-017-0147-3, @doi:10.3389/fphar.2018.01157].
```
@RLordan's suggestion that got lost while I was trying to figure out how to merge in all the suggestions!

2021-01-27 22:04 UTC, agitter requested changes

2021-01-27 22:04 UTC, agitter commented on content/20.pharmaceuticals.md
> +In both studies, anakinra seemed to improve respiratory function, decrease the likelihood of requiring invasive mechanical ventilation, and in Paris, it significantly reduced mortality [@doi:10.1016/
```suggestion
In both studies, anakinra seemed to improve respiratory function, decrease the likelihood of requiring invasive mechanical ventilation, and in Paris, it significantly reduced mortality [@doi:10/gg4smj]. 
```

Can we be more precise?  "Seemed to improve" sounds qualitative, whereas other trial summaries have been more quantitative.

2021-01-27 22:04 UTC, agitter commented on content/20.pharmaceuticals.md
> +Similar observation was made in [@doi:10.1007/s11739-020-02600-z], where anakinra was used as a second tier after no response to standard corticosteroids or combination of corticosteroids and tociliz
```suggestion
A similar observation was made in [@doi:10.1007/s11739-020-02600-z], where anakinra was used as a second tier after no response to standard corticosteroids or combination of corticosteroids and tocilizumab treatments.
```

What was the result of this trial?

2021-01-27 22:04 UTC, agitter commented on content/20.pharmaceuticals.md
> +In another retrospective cohort study carried by Radboud University Medical Center (Nijmegen, The Netherlands) and Bernhoven Hospital (Uden, The Netherlands), Anakinra was found to effectively reduce
```suggestion
In another retrospective cohort study carried by Radboud University Medical Center (Nijmegen, The Netherlands) and Bernhoven Hospital (Uden, The Netherlands), Anakinra was found to effectively reduce hyperinflammation clinical signs for critically ill patients [@doi:10.1186/s13054-020-03364-w]. 
```

As above, I recommend being more quantitative about what we mean by "effectively reduce".

2021-01-27 22:04 UTC, agitter commented on content/20.pharmaceuticals.md
> +The previous findings were not confirmed in a recent randomized clinical trial carried in 16 hospitals in France, which included 116 patients, with 59 in anakinra cohort and 57 in control group.
```suggestion
The previous findings were not confirmed in a recent randomized clinical trial carried in 16 hospitals in France, which included 116 patients, with 59 in the anakinra cohort and 57 in the control group. 
```

2021-01-27 22:04 UTC, agitter commented on content/20.pharmaceuticals.md
> +In this study anakinra was not confirmed to reduce mortality for COVID-19 and mild-to-moderate pneumonia patients treated intravenously.
Same request, can you please add more about the trial results or statistics?

2021-01-27 22:04 UTC, agitter commented on content/20.pharmaceuticals.md
> +Anakinra may be a promising treatment option worthy of further investigation for patients with severe forms of COVID-19.
This conclusion seems too strong or optimistic to me given the evidence above.

2021-01-27 22:06 UTC, rando2 reviewed
This is just some preliminary formatting feedback. I think it would be good to include a bit of additional info about these studies (namely, what was SOC? what were the primary and secondary outcomes? what were the statistical differences between the two groups?) 

I'm happy to help with this but have a few other things I need to wrap up tonight, so I won't be able to contribute until tomorrow!

2021-02-02 23:27 UTC, rando2 commented
Hey @athril, I wasn't sure if you needed help fleshing this out or responding to mine and @agitter's feedback? We are getting close to needing to send the paper out to authors. I can definitely just add a sentence to note that this drug in the same category as TCZ is under consideration, if it would be easier to expand on it moving forward!

2021-02-02 23:51 UTC, athril commented
Hi! I will take a look at it tomorrow. Thank you!

On Tue, Feb 2, 2021, 6:27 PM HM Rando <notifications@github.com> wrote:

> Hey @athril <https://github.com/athril>, I wasn't sure if you needed help
> fleshing this out or responding to mine and @agitter
> <https://github.com/agitter>'s feedback? We are getting close to needing
> to send the paper out to authors. I can definitely just add a sentence to
> note that this drug in the same category as TCZ is under consideration, if
> it would be easier to expand on it moving forward!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/greenelab/covid19-review/pull/757#issuecomment-772085982>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC26CM7BV5BJBVSUANIUJITS5CC7BANCNFSM4WBPO37A>
> .
>

2021-03-10 19:00 UTC, agitter commented
If we're still interested in anakinra, we can create an issue for this new trial: https://doi.org/10.7554/eLife.66125

2021-03-10 23:26 UTC, RLordan commented
> If we're still interested in anakinra, we can create an issue for this new trial: https://doi.org/10.7554/eLife.66125

@athril led on this one

2021-03-12 05:25 UTC, athril reviewed
> If we're still interested in anakinra, we can create an issue for this new trial: https://doi.org/10.7554/eLife.66125

Thanks for sharing!
This trial doesn't change much in my opinion. Anakinra remains an interesting lead, but the number of participants is too small to make a substantial difference.

2021-04-15 22:03 UTC, rando2 commented
Closing this PR due to the new paper structure

2021-04-15 22:03 UTC, closed without merging