Maybe mention living WHO therapeutics guidelines
greenelab/covid19-review pull request #992
Opened 2021-08-10 20:36 UTC by dziakj1

I'm not a co-author on this one but I thought it might be good for you to also mention the living guidelines article at #991 which would be interesting to readers of this article.
  

### Related issues

#991

### Suggested reviewers (optional)

@rando2

### Checklist

- [x] Text is formatted so that each sentence is on its own line.

- [x] Pre-prints cited in this pull request have a GitHub issue opened so that they can be reviewed.

2021-08-11 21:06 UTC, agitter requested changes
I agree we should reference this related project as well as the connected systematic review.  I added both citations in my suggestion.

2021-08-11 21:06 UTC, agitter commented on content/20.pharmaceuticals.md
> +Summary information can also be found in the World Health Organization's living guidelines document for COVID-19 therapeutics
```suggestion
The WHO guidelines [@doi:10.1136/bmj.m3379] and a systematic review [@doi:10.1136/bmj.m2980] are complementary living documents that summarize COVID-19 therapeutics.
```

2021-08-11 21:31 UTC, rando2 approved these changes

2021-08-16 12:54 UTC, rando2 commented
@agitter is it OK with you if I merge this?

2021-08-16 12:56 UTC, agitter commented
> is it OK with you if I merge this?

Yes, looks good to me

2021-08-16 12:58 UTC, merged